_target_: paper_src.models.RNNLatentSAE
rnn_cell:
  _target_: paper_src.models.AblatedNODECell
  input_size: 1
  hidden_size: ${model.latent_size}
  dt: null
input_size: ${datamodule.obs_dim}
encoder_size: 64
latent_size: 3
learning_rate: 1.0e-3
weight_decay: 0.0
dropout: 0.05
points_per_group: 20
epochs_per_group: 500
