_target_: paper_src.models.RNNLatentSAE
rnn_cell:
  _target_: torch.nn.GRUCell
  input_size: 1
  hidden_size: ${model.latent_size}
input_size: ${datamodule.obs_dim}
encoder_size: 64
latent_size: 25
learning_rate: 1.0e-3
weight_decay: 1.0e-4
dropout: 0.05
points_per_group: 70
epochs_per_group: 3000
