_target_: paper_src.models.RNNLatentSAE
rnn_cell:
  _target_: paper_src.models.AblatedNODECell
  input_size: 1
  hidden_size: ${model.latent_size}
  mlp_hidden_dims: [128]
  dt: 0.1
input_size: ${datamodule.obs_dim}
encoder_size: 64
latent_size: 10
learning_rate: 5.0e-4
weight_decay: 0.0
dropout: 0.05
points_per_group: 20
epochs_per_group: 500
